apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-password: 'mysecretpassword'
# kubectl create secret generic postgres-secret --from-literal=postgres-password=password
