apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: password
# kubectl create secret generic postgres-secret --from-literal=postgres-password=password
