LogFilePath: "./agent.log"
Interval: 10
Kafka:
  Brokers:
    - "localhost:9092"
  Topic: "system-metrics"
HTTP:
  Endpoint: "" # Leave blank to disable HTTP exporter
Monitors:
  CPU: true
  Memory: true
  Disk: true
  Network: true
Thresholds:
  CPU: 8
  Memory: 85
  Disk: 90
