Tenant:
  # Unique identifier for the organization/tenant (temporarily optional)
  # Note: Tenant ID requirement is temporarily disabled
  ID: "67a5da7f9f3f88e40759e219"
  # API key for authentication (optional)
  # Note: API key is optional - if provided, it will be used for authentication
  APIKey: "sms_00305567449e4cb9e492bc09811e6fdbf16635a3ab7235f9"
  # Tenant organization name
  Name: "Development Standard"
  # Environment (e.g., production, staging, development)
  Environment: "development"
  # Tenant type (e.g., enterprise, standard, basic)
  Type: "standard"
  # Tenant-specific endpoint overrides (optional)
  Endpoints:
    Metrics: "https://security.dev/gateway/api/v1/system-metrics/ingest"
    HealthCheck: "https://security.dev/gateway/api/v1/health"
    KeyValidation: "https://security.dev/gateway/api/v1/validate-key"
  # Tenant-specific collection rules
  CollectionRules:
    # List of enabled metric types
    EnabledMetrics:
      - "cpu"
      - "memory"
      - "disk"
      - "network"
      - "processes"
    # Collection frequency override (in seconds)
    SampleRate: 10
    # Data retention period (in days)
    RetentionDays: 7

# General logging configuration
LogFilePath: "./agent.log"
LogSettings:
  Level: "info"
  Format: "json"
  MaxSize: 100 # MB
  MaxBackups: 3
  MaxAge: 28 # days
  Compress: true

# Metrics collection interval in seconds
Interval: 10

# Kafka configuration
Kafka:
  Brokers:
    - "localhost:9092"
  Topic: "system-metrics"
  # Tenant-specific Kafka settings
  TenantTopic: "tenant-{id}-metrics" # {id} will be replaced with tenant ID
  SecurityProtocol: "plaintext"
  SASLMechanism: ""
  Username: ""
  Password: ""

# HTTP configuration
HTTP:
  StorageDir: "./storage"
  RetryAttempts: 3
  RetryDelay: 5 # seconds
  Timeout: 30 # seconds
  Headers:
    TenantID: "X-Tenant-ID"
    APIKey: "X-API-Key"

# Monitor configurations
Monitors:
  CPU: true
  Memory: true
  Disk: true
  Network: true
  Process: true # Added process monitoring

# Alert thresholds (percentage)
Thresholds:
  CPU: 80
  Memory: 85
  Disk: 90
  NetworkUtilization: 80

# Storage configuration
Storage:
  # Tenant-specific storage settings
  MaxStoragePerTenant: 1024 # MB
  RetentionPeriod: 7 # days
  CompressOldData: true

# Security settings
Security:
  EncryptData: true
  ValidateSSL: false
  AllowedIPs: [] # Empty array means no IP restrictions
  TLS:
    CertFile: "security.dev.crt"
    KeyFile: "security.dev.key"
