apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  # Development/testing domain (change before production deployment)
  DOMAIN_NAME: "security.dev"
  CORS_ALLOWED_ORIGINS: "https://*.security.dev"
