apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-migrations
data:
  # Note: The SQL content will be populated by kubectl create configmap
  # Use: kubectl create configmap postgres-migrations --from-file=logs.sql --from-file=alerts.sql
  # This comment serves as a reminder of how to properly create this ConfigMap
