apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-migrations
data:
  # Import centralized schemas
  logs.sql: |
    \i /schemas/postgresql/log-aggregator/logs.sql
  alerts.sql: |
    \i /schemas/postgresql/log-aggregator/alerts.sql
