apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrations
spec:
  template:
    spec:
      containers:
        - name: migrations
          image: postgres:14
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for PostgreSQL to be ready
              until pg_isready -h postgres-srv -p 5432; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 2
              done

              # Apply schemas in order
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-srv -U $POSTGRES_USER -d $POSTGRES_DB -f /migrations/logs.sql
              PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-srv -U $POSTGRES_USER -d $POSTGRES_DB -f /migrations/alerts.sql

              echo "Database schemas applied successfully"
          env:
            - name: POSTGRES_DB
              value: logdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: migrations
              mountPath: /migrations
            - name: schemas
              mountPath: /schemas
      volumes:
        - name: migrations
          configMap:
            name: postgres-migrations
        - name: schemas
          configMap:
            name: postgres-schemas
      restartPolicy: OnFailure
